import time 
#______________________________________________________
User = input ("Hello, please enter your name first ")
time.sleep(1)
User2 = print("Welcome to 10Quiz " + User)
time.sleep(1)
print("So this is a quiz and you need to slove different riddles")
time.sleep(5)
print("In this version there are 10")
time.sleep(4)
print("And there is a first")
time.sleep(2)
print("Question 1")
time.sleep(2)
points = True
while points == True:
    points = (0)
#1
print("Where was Salvador Dali born?")
time.sleep(5)
I = print("1. France")
time.sleep(1)
II = print("2. Kanada")
time.sleep(1)
III = print("3. Spain")
time.sleep(1)
IV = print ("4. Norway")
time.sleep(1)
Qes = input("Enter the answer: ")
if Qes == ("Spain") or Qes == ("spain") or Qes == ("1"):
    time.sleep(1)
    print("Correct!")
    time.sleep(2)
    points +=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
else:
    print("Incorrect!")
    time.sleep(2)
    points -=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
#2
print("Question 2")
time.sleep(2)
print("What is the capital city of USA?")
time.sleep(5)
I = print("1. Madrid")
time.sleep(1)
II = print("2. Wellington")
time.sleep(1)
III = print("3. Washington")
time.sleep(1)
IV = print ("4. Oslo")
time.sleep(1)
Qes = input("Enter the answer: ")
if Qes == ("Washington") or Qes == ("washington") or Qes == ("3"):
    time.sleep(1)
    print("Correct!")
    time.sleep(2)
    points +=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
else:
    print("Incorrect!")
    time.sleep(2)
    points -=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
#3
print("Question 3")
time.sleep(2)
print("What's company invent the first laptop?")
time.sleep(5)
I = print("1. HP")
time.sleep(1)
II = print("2. IBM")
time.sleep(1)
III = print("3. Microsoft")
time.sleep(1)
IV = print ("4. Xiaomi")
time.sleep(1)
Qes = input("Enter the answer: ")
if Qes == ("IBM") or Qes == ("ibm") or Qes == ("Ibm") or Qes == ("2"):
    time.sleep(1)
    print("Correct!")
    time.sleep(2)
    points +=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
else:
    print("Incorrect!")
    time.sleep(2)
    points -=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
#4
print("Question 4")
time.sleep(2)
print("Which the last version of 'Minecraft'?")
time.sleep(5)
I = print("1. 1.8")
time.sleep(1)
II = print("2. 1.14")
time.sleep(1)
III = print("3. 1.17")
time.sleep(1)
IV = print ("4. 1.19")
time.sleep(1)
Qes = input("Enter the answer: ")
if Qes == ("1.19") or Qes == ("1 19"):
    time.sleep(1)
    print("Correct!")
    time.sleep(2)
    points +=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
else:
    print("Incorrect!")
    time.sleep(2)
    points -=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
#5
print("Question 5")
time.sleep(2)
print("How many countries on the earth?")
time.sleep(5)
I = print("1. 2256")
time.sleep(1)
II = print("2. 453/456")
time.sleep(1)
III = print("3. 17")
time.sleep(1)
IV = print ("4. 197/198")
time.sleep(1)
Qes = input("Enter the answer: ")
if Qes == ("197") or Qes == ("198") or Qes == ("197/198") or Qes == ("197 198"):
    time.sleep(1)
    print("Correct!")
    time.sleep(2)
    points +=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
else:
    print("Incorrect!")
    time.sleep(2)
    points -=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
#6
print("Question 6")
time.sleep(2)
print("When Michael Jacson die?")
time.sleep(5)
I = print("1. 2009")
time.sleep(1)
II = print("2. 1999")
time.sleep(1)
III = print("3. 1989")
time.sleep(1)
IV = print ("4. 2015")
time.sleep(1)
Qes = input("Enter the answer: ")
if Qes == ("2009"):
    time.sleep(1)
    print("Correct!")
    time.sleep(2)
    points +=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
else:
    print("Incorrect!")
    time.sleep(2)
    points -=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
#7
print("Question 7")
time.sleep(2)
print("which football team is most popular in the world?")
time.sleep(5)
I = print("1. Manchester city")
time.sleep(1)
II = print("2. Barcelona 'FCB'")
time.sleep(1)
III = print("3. Royal Madrid")
time.sleep(1)
IV = print ("4. Macabi Tel-Aviv")
time.sleep(1)
Qes = input("Enter the answer: ")
if Qes == ("Barcelona") or Qes == ("barcelona") or Qes == ("fcb") or Qes == ("FCB") or Qes == ("Fcb"):
    time.sleep(1)
    print("Correct!")
    time.sleep(2)
    points +=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
else:
    print("Incorrect!")
    time.sleep(2)
    points -=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
#8
print("Question 8")
time.sleep(2)
print("Which the easiest code language to beginers?")
time.sleep(5)
I = print("1. C++")
time.sleep(1)
II = print("2. Java Script")
time.sleep(1)
III = print("3. PHP")
time.sleep(1)
IV = print ("4. Python")
time.sleep(1)
Qes = input("Enter the answer: ")
if Qes == ("Python") or Qes == ("python"):
    time.sleep(1)
    print("Correct!")
    time.sleep(2)
    points +=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
else:
    print("Incorrect!")
    time.sleep(2)
    points -=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
#9
print("Question 9")
time.sleep(2)
print("What's company make the most popular portative console in the world?")
time.sleep(5)
I = print("1. Sony/Playstation")
time.sleep(1)
II = print("2. Playdate")
time.sleep(1)
III = print("3. Valve")
time.sleep(1)
IV = print ("4. Nintendo")
time.sleep(1)
Qes = input("Enter the answer: ")
if Qes == ("Nintendo") or Qes == ("nintendo"):
    time.sleep(1)
    print("Correct!")
    time.sleep(2)
    points +=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
else:
    print("Incorrect!")
    time.sleep(2)
    points -=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
#10
print("Question 10")
time.sleep(2)
print("Whats name of PS5 controller?")
time.sleep(5)
I = print("1. DualShock 5")
time.sleep(1)
II = print("2. DualSence")
time.sleep(1)
III = print("3. PS5 Controller")
time.sleep(1)
IV = print ("4. It doesn't have a name")
time.sleep(1)
Qes = input("Enter the answer: ")
if Qes == ("DualSence") or Qes == ("Dual Sence") or Qes == ("Dualsence") or Qes == ("Dual sence") or Qes == ("dualsence") or Qes == ("dual sence") or Qes == ("dualSence"):
    time.sleep(1)
    print("Correct!")
    time.sleep(2)
    points +=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
else:
    print("Incorrect!")
    time.sleep(2)
    points -=1
    print("Points:")
    time.sleep(1)
    print(points)
    time.sleep(1)
print("You earn:")
time.sleep(2)
int(print(points))
time.sleep(2)
if points >= 0:
    print("points :(")
else:
    print("points :)")
time.sleep(2)
print("Ok " + User + "the quiz is end/nbut if you can wait, new version is coming soon with 20 Questions and new functions.")
time.sleep(10)
print("Thank you " + User + " for using our game! (We are one :))")
time.sleep(5)
print("And... Why have today birthday 'Happy birthday!:) ")
time.sleep(5)
print("Arcade create 2022 all rights recerved")
time.sleep(3)
print("Powered by Python")
time.sleep(2)
print("The program will close in (5)")
time.sleep(1)
print("The program will close in (4)")
time.sleep(1)
print("The program will close in (3)")
time.sleep(1)
print("The program will close in (2)")
time.sleep(1)
print("The program will close in (1)")
time.sleep(1)